version: 2
updates:
  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    commit-message:
      prefix: "⬆ "
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "⬆ "
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "⬆ "
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
