apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nav-persondata-api
  namespace: holmes
  labels:
    team: holmes
spec:
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      singlePageApplication: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
    sidecar:
      enabled: true
  image: {{image}}
  liveness:
    path: /actuator/health
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /actuator/health
    port: 8080
    initialDelay: 20
    timeout: 60
  ingresses:
    - https://nav-persondata-api.intern.dev.nav.no
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "actuator/metrics"
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: oppslag-bruker-frontend
          namespace: holmes
          cluster: dev-gcp
    outbound:
      rules:
        - application: sokos-utbetaldata
          namespace: okonomi
          cluster: dev-fss
        - application: ikomp-q2
          namespace: team-inntekt
          cluster: dev-fss
        - application: populasjonstilgangskontroll
          namespace: tilgangsmaskin
      external:
        - host: sokos-utbetaldata.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: ikomp-q2.dev-fss-pub.nais.io
  env:
    - name: UTBETALING_SCOPE
      value: api://dev-fss.okonomi.sokos-utbetaldata/.default
    - name: UTBETALING_URL
      value: https://sokos-utbetaldata.dev-fss-pub.nais.io

    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql

    - name: INNTEKT_SCOPE
      value: api://dev-fss.team-inntekt.ikomp-q2/.default
    - name: INNTEKT_URL
      value: https://ikomp-q2.dev-fss-pub.nais.io

    - name: TILGANGMASKIN_SCOPE
      value: api://dev-gcp.tilgangsmaskin.populasjonstilgangskontroll/.default
    - name: TILGANGMASKIN_URL
      value: https://tilgangsmaskin.intern.dev.nav.no