application:
  name: nav-persondata-api
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  endpoint:
    health:
      show-details: always
no.nav.security.jwt:
  issuer:
    azuread:
      discoveryurl: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration"
      accepted_audience: "f99254b7-a630-48fe-a21a-21989eca6f4b"
NAIS_TOKEN_ENDPOINT: http://127.0.0.1:7164/api/v1/token
NAIS_TOKEN_INTROSPECTION_ENDPOINT : http://127.0.0.1:7164/api/v1/introspect
NAIS_TOKEN_EXCHANGE_ENDPOINT: http://127.0.0.1:7164/api/v1/token/exchange
PDL_SCOPE: api://dev-fss.pdl.pdl-api/.default
PDL_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
UTBETALING_SCOPE: api://dev-fss.okonomi.sokos-utbetaldata/.default
UTBETALING_URL: https://sokos-utbetaldata.dev-fss-pub.nais.io

INNTEKT_SCOPE: api://dev-fss.team-inntekt.ikomp-q2/.default
INNTEKT_URL: https://ikomp-q2.dev-fss-pub.nais.io

TILGANGMASKIN_SCOPE: api://dev-gcp.tilgangsmaskin.populasjonstilgangskontroll/.default
TILGANGMASKIN_URL: https://tilgangsmaskin.intern.dev.nav.no

AAREG_SCOPE: api://dev-fss.arbeidsforhold.aareg-services-nais/.default
AAREG_URL: https://aareg-services.dev-fss-pub.nais.io/api


EREG_URL: https://ereg-services.dev.intern.nav.no/api


