name: Deploy release til prod
permissions:
  contents: "read"
  id-token: "write"
  packages: "write"
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag som skal deployes'
        required: true

env:
  TARGET_REF: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
  IMAGE: ${{ github.event_name == 'workflow_dispatch' && format('ghcr.io/{0}:{1}', github.repository, github.event.inputs.tag) || format('ghcr.io/{0}:{1}', github.repository, github.ref_name) }}
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ env.TARGET_REF }}
      - name: test and build
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
      - run: ./gradlew test bootJar
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: holmes # required
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
  deployprod:
    name: Deploy til Prod
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ env.TARGET_REF }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod.yaml
          IMAGE: ${{ needs.build_and_push.outputs.image }}
          TELEMETRY: ${{ needs.build_and_push.outputs.telemetry }}
